apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "config-reloader-controller.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "config-reloader-controller.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "config-reloader-controller.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "config-reloader-controller.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "config-reloader-controller.fullname" . }}
      containers:
      - name: manager
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
        - "--leader-elect"
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}