# This rule is not used by the project config-reloader-controller itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the configreloader.rahmatnugraha.top.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: config-reloader-controller
    app.kubernetes.io/managed-by: kustomize
  name: configreloader-editor-role
rules:
- apiGroups:
  - configreloader.rahmatnugraha.top
  resources:
  - configreloaders
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - configreloader.rahmatnugraha.top
  resources:
  - configreloaders/status
  verbs:
  - get
